server-name: eu-smp-1
server-region: Europe

scoreboard:
  enabled: true
  title: "&b&lᴅᴇʟᴛᴀ &7︱ &fѕᴍᴘ"
  lines:
    - ""
    - "&bᴘʟᴀʏᴇʀ"
    - " &b❚ &fʀᴀɴᴋ: %rank-color%%rank%"
    - " &b❚ &fᴄᴏɪɴѕ: &b$%coins%"
    - " &b❚ &fᴅᴇᴀᴛʜѕ: &b%deaths%"
    - " &b❚ &fᴋɪʟʟѕ: &b%kills%"
    - " &b❚ %combat-tag%"
    - ""
    - "&7ᴘʟᴀʏ.ʀᴇᴠᴇʀᴇ.ᴅᴇᴠ"
  combat-tag:
    lines:
      - ""
      - " &b❚ &fᴄᴏᴍʙᴀᴛ ʟᴏɢ: &b%tag%ѕ"

teleport-spawn:
  enabled: true
  only-first-join: true
  on-death:
    enabled: true
    only-without-bed: true

tips:
  enabled: true
  interval: 120
  announcements:
    message-1:
      - " "
      - "&4&lALERT &7- &cAttention!"
      - "&fReminder to bring along your friends on this adventure!"
      - "&fJoin &bplay.revere.dev &ftoday!"
      - " "
    message-2:
      - " "
      - "&4&lALERT &7- &cAttention!"
      - "&fJoin our Discord server for the latest updates!"
      - "&bhttps://discord.gg/4bbVFypmzh"
      - ""
    message-3:
        - " "
        - "&4&lALERT &7- &cAttention!"
        - "&fWould you like to apply for staff?"
        - "&bhttps://forms.gle/UrRgXDRZ8UY7s6LM8"
        - " "