server-name: eu-smp-1
server-region: Europe

scoreboard:
  enabled: true
  title: "{#0544AC>}&lRevere{#2188EB<}"
  lines:
    - ""
    - " &fKills: &b%kills%"
    - " &fDeaths: &b%deaths%"
    - ""
    - "&7play.revere.dev"